### ISSUE TITLE
Local Testing

### ISSUE THREAD

**Issue by ajinkya** [developmentseed/cogeo-tiler#2]
Thank you for this wonderful project. I learnt a lot from this.

In the code I see that there is a cli.py that mentions local testing. How do I execute this locally?
Is there a ideal local development REPL setup, that you follow?

Also, I would like to contribute towards documenting this project, if that is in the road-map.

Thanks.

**Comment by vincentsarago** [comment]
👋 @ajinkya thanks for this issue.

if you did `pip install .` after downloading this repo you can simply run `cogeo-tiler` command in your shell (https://github.com/developmentseed/cogeo-tiler/blob/master/setup.py#L36) 

We definitely need better docs here, feel free to open Issues/PR
