### ISSUE TITLE
Error deploying to eu-west-1

### ISSUE THREAD

**Issue by adrianmelero** [developmentseed/cogeo-tiler#4]
When executing sls deploy ( modifying region on serverles.yml to eu-west-1)

The error code is:

User: arn:aws:iam::xxxxxxxxxxx:user/xxxxxxxxxxxxxx is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:eu-west-1:524387336408:layer:gdal30-py37-cogeo:8 (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: b36426f7-2d28-4241-9194-9711705e789a)

It seems that is a region/zone problem, I need to deploy it on eu-west-1.

Thanks.

**Comment by vincentsarago** [comment]
Hi @adrianmelero this is because the lambda layer is not present in eu-west-1 

I still need to update this repo to use https://github.com/lambgeo/geo-layer (which is also not deployed in eu-west-1)

There is no quick solution to this, I'll try to update this repo over the week end

**Comment by adrianmelero** [comment]
Hi @vincentsarago many thanks for that.

**Comment by vincentsarago** [comment]
@adrianmelero It should be fixed now ;-)
