### ISSUE TITLE
Does it support vsis3?

### ISSUE THREAD

**Issue by adrianmelero** [developmentseed/cogeo-tiler#6]
I'm getting this error while passing a s3://bucket-name/AB000a12_001_MUL_L1T_COG3.tif in the api url:

 {"errorMessage": "'/vsis3/bucket-name/AB000a12_001_MUL_L1T_COG3.tif' not recognized as a supported file format."}

thanks.

**Comment by vincentsarago** [comment]
Hi @adrianmelero it should work. just make sure to add `bucket-name` in https://github.com/developmentseed/cogeo-tiler/blob/master/serverless.yml#L21-L27

**Comment by adrianmelero** [comment]
Hi @vincentsarago yes, It is added, but still not working when passing url s3 object to the API

**Comment by adrianmelero** [comment]
It was a problem of permissions, I have added Access Key and Secret Key to Dockerfile and now its working, thanks!!!
